import Footer from "@/components/Footer/Footer";
import '@/Styles/global.css';
import '@/Styles/Font/font.css';
import Navbar from "@/components/navbar/navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MainLayout({ children }) {
    return (
      <>
        <Navbar />
        <main className="main-content">
          {children}
        </main>
        <Footer />
      </>
    );
  }
