import Footer from "@/components/Footer/Footer";
import { Geist, Geist_Mono } from "next/font/google";
import '@/Styles/global.css';
import '@/Styles/Font/font.css';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
    <body>
        <main>
            {children}
        </main>
        <Footer />
    </body>
</html>
);
}
